[package]
org = "ballerinax"
name = "asb"
version = "0.1.3"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Azure","ServiceBus"]
repository = "https://github.com/ballerina-platform/module-ballerinax-azure-service-bus"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
path = "../asb-native/target/asb-native-1.0.2-jar-with-dependencies.jar"
groupId = "org.ballerinalang"
artifactId = "asb-native"
module = "asb-native" 
version = "1.0.0"
