name: PR Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
          JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
        run: ./gradlew build --scan --no-daemon
        
      # Build Ballerina Project
      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action/@nightly
        with:
          args:
            pack ./asb-ballerina
        env:
            JAVA_HOME: /usr/lib/jvm/default-jvm

      # Test Ballerina Project
      - name: Ballerina Test
        uses: ballerina-platform/ballerina-action/@nightly
        with:
          args:
            test ./asb-ballerina
        env:
            JAVA_HOME: /usr/lib/jvm/default-jvm
            CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
            QUEUE_NAME: ${{ secrets.QUEUE_NAME }}
            TOPIC_NAME: ${{ secrets.TOPIC_NAME }}
            SUBSCRIPTION_NAME1: ${{ secrets.SUBSCRIPTION_NAME1 }}
            SUBSCRIPTION_NAME2: ${{ secrets.SUBSCRIPTION_NAME2 }}
            SUBSCRIPTION_NAME3: ${{ secrets.SUBSCRIPTION_NAME3 }}

