# This is a basic workflow to help you get started with Actions

name: Deployment

# Controls when the action will run.
# Triggers the workflow on release.
on:
  release:
    types:  [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Set up Java Environment
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: 'Create settings.xml'
        run: |
            echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                        http://maven.apache.org/xsd/settings-1.0.0.xsd">
                    <activeProfiles>
                       <activeProfile>github</activeProfile>
                    </activeProfiles>
                    <profiles>
                      <profile>
                        <id>github</id>
                        <repositories>
                          <repository>
                            <id>central</id>
                            <url>https://repo1.maven.org/maven2</url>
                            <releases><enabled>true</enabled></releases>
                            <snapshots><enabled>true</enabled></snapshots>
                          </repository>
                          <repository>
                            <id>github</id>
                            <name>GitHub ballerina-platform Apache Maven Packages</name>
                            <url>https://maven.pkg.github.com/ballerina-platform/ballerina-lang</url>
                          </repository>
                        </repositories>
                      </profile>
                    </profiles>
                    <servers>
                      <server>
                        <id>github</id>
                        <username>${{ secrets.USERNAME }}</username>
                        <password>${{ secrets.PERSONAL_TOKEN }}</password>
                      </server>
                    </servers>
                  </settings>' > ~/.m2/settings.xml

      - working-directory: ./asb-native
        run: mvn clean package

      # Build Ballerina Project
      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action/@swan-lake-connector-release
        with:
          args:
            build -c --skip-tests ./asb-ballerina
        env:
          JAVA_HOME: /usr/lib/jvm/default-jvm
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
          QUEUE_PATH: ${{ secrets.QUEUE_PATH }}
          TOPIC_PATH: ${{ secrets.TOPIC_PATH }}
          SUBSCRIPTION_PATH1: ${{ secrets.SUBSCRIPTION_PATH1 }}
          SUBSCRIPTION_PATH2: ${{ secrets.SUBSCRIPTION_PATH2 }}
          SUBSCRIPTION_PATH3: ${{ secrets.SUBSCRIPTION_PATH3 }}

      # Push to Ballerina Central
      - name: Ballerina Push
        uses: ballerina-platform/ballerina-action/@swan-lake-connector-release
        with:
          args:
            push
        env:
          WORKING_DIR: ./asb-ballerina
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
          JAVA_HOME: /usr/lib/jvm/default-jvm
